### ISSUE TITLE
CORS error on demo site

### ISSUE THREAD

**Issue by knightshade23** [creativetimofficial/ct-material-dashboard-react-pro-nodejs#3]
# Expected Behavior

Please describe the behavior you are expecting
To be able to access the demo site to do a live preview at:
https://material-dashboard-pro-react-nodejs.creative-tim.com/auth/login

# Current Behavior

What is the current behavior?
One cannot get past the login screen

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Visit (https://material-dashboard-pro-react-nodejs.creative-tim.com/auth/login)
2. Click Sign In
3. Nothing visible happens.
  (If you look, there are CORS errors.  If one attepts that call in Postman - there is a Cloudflare error)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: macOS
* Operating System:
* Browser and Version: Chrome and Safari

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM. 

We have fixed the issue. Thank you for bringing it to our attention. 

Best.
